name: hankofiles
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.8.1
  file_picker: ^5.5.0
  injectable: ^2.3.1
  get_it: ^7.6.4
  dio: ^5.3.3
  go_router: ^11.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  elegant_notification: ^1.11.2
  jiffy: ^6.2.1
  flutter_colorpicker: ^1.0.3
  speed_dial_fab: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.3


flutter:
  uses-material-design: true
  assets:
    - images/
        
    
    
                                      