name: hankofiles
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.21
  file_picker: ^5.5.0
  injectable: ^2.3.1
  get_it: ^7.6.4
  dio: ^5.3.3
  go_router: ^11.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

        
    
    
                                      